### ISSUE TITLE
SharedInternPool.Intern(string?) returns string.Empty on null values

### ISSUE THREAD

**Issue by vonzshik** [benaadams/Ben.StringIntern#37]
Hello! Just wanted to clarify: is this an intended behavior?

https://github.com/benaadams/Ben.StringIntern/blob/1fecf39ad1192b2a2bfd3f1d9a6d932f66e0cba3/src/SharedInternPool.cs#L58-L60

**Comment by benaadams** [comment]
🤔... it should probably keep null as null

**Comment by benaadams** [comment]
Thank you!

**Comment by vonzshik** [comment]
And thank you for fixing it so quickly!
